# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1404, 900)
        MainWindow.setStyleSheet("border-raduis: 1px")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:0.21, x2:1, y2:1, stop:0 rgba(199, 103, 107, 255), stop:1 rgba(248, 161, 121, 255));")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.side_menu = QtWidgets.QFrame(self.centralwidget)
        self.side_menu.setMinimumSize(QtCore.QSize(0, 0))
        self.side_menu.setMaximumSize(QtCore.QSize(300, 16777215))
        self.side_menu.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.side_menu.setStyleSheet("background-color: rgb(157, 81, 88);")
        self.side_menu.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.side_menu.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.side_menu.setObjectName("side_menu")
        self.gridLayout = QtWidgets.QGridLayout(self.side_menu)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.toolButton_4 = QtWidgets.QToolButton(self.side_menu)
        self.toolButton_4.setMaximumSize(QtCore.QSize(500, 70))
        self.toolButton_4.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.toolButton_4.setStyleSheet("background-color: rgb(255, 202, 71);\n"
"border-radius: 30px;\n"
"color: white;\n"
"font: 700 22pt \"Segoe UI Variable Display\";")
        self.toolButton_4.setObjectName("toolButton_4")
        self.gridLayout.addWidget(self.toolButton_4, 6, 0, 1, 1)
        self.toolButton = QtWidgets.QToolButton(self.side_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton.sizePolicy().hasHeightForWidth())
        self.toolButton.setSizePolicy(sizePolicy)
        self.toolButton.setMaximumSize(QtCore.QSize(500, 70))
        self.toolButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.toolButton.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.toolButton.setStyleSheet("background-color: rgb(255, 202, 71);\n"
"border-radius: 30px;\n"
"color: white;\n"
"font: 700 22pt \"Segoe UI Variable Display\";")
        self.toolButton.setObjectName("toolButton")
        self.gridLayout.addWidget(self.toolButton, 2, 0, 1, 1)
        self.toolButton_3 = QtWidgets.QToolButton(self.side_menu)
        self.toolButton_3.setMaximumSize(QtCore.QSize(500, 70))
        self.toolButton_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.toolButton_3.setStyleSheet("background-color: rgb(255, 202, 71);\n"
"border-radius: 30px;\n"
"color: white;\n"
"font: 700 22pt \"Segoe UI Variable Display\";")
        self.toolButton_3.setObjectName("toolButton_3")
        self.gridLayout.addWidget(self.toolButton_3, 5, 0, 1, 1)
        self.toolButton_2 = QtWidgets.QToolButton(self.side_menu)
        self.toolButton_2.setMaximumSize(QtCore.QSize(500, 70))
        self.toolButton_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.toolButton_2.setStyleSheet("background-color: rgb(255, 202, 71);\n"
"border-radius: 30px;\n"
"color: white;\n"
"font: 700 22pt \"Segoe UI Variable Display\";")
        self.toolButton_2.setObjectName("toolButton_2")
        self.gridLayout.addWidget(self.toolButton_2, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(41, 56, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.side_menu, 0, 0, 1, 1)
        self.main_menu = QtWidgets.QStackedWidget(self.centralwidget)
        self.main_menu.setObjectName("main_menu")
        self.vocabulaire_page = QtWidgets.QWidget()
        self.vocabulaire_page.setObjectName("vocabulaire_page")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.vocabulaire_page)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.title_frame = QtWidgets.QFrame(self.vocabulaire_page)
        self.title_frame.setMaximumSize(QtCore.QSize(16777215, 200))
        self.title_frame.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.title_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.title_frame.setObjectName("title_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.title_frame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.title_frame)
        font = QtGui.QFont()
        font.setFamily("Sitka Heading Semibold")
        font.setPointSize(61)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(255, 202, 71);\n"
"background-color: rgba(255, 255, 255,0);")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.title_frame, 0, 0, 1, 1)
        self.content_frame = QtWidgets.QFrame(self.vocabulaire_page)
        self.content_frame.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.content_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.content_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.content_frame.setObjectName("content_frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.content_frame)
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.gridLayout_3.setContentsMargins(50, 0, 23, 0)
        self.gridLayout_3.setHorizontalSpacing(16)
        self.gridLayout_3.setVerticalSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btn_vrb_lvl1 = QtWidgets.QPushButton(self.content_frame)
        self.btn_vrb_lvl1.setMinimumSize(QtCore.QSize(0, 60))
        self.btn_vrb_lvl1.setMaximumSize(QtCore.QSize(260, 16777215))
        self.btn_vrb_lvl1.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_vrb_lvl1.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(102, 109, 198); \n"
"font: 700 20pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.btn_vrb_lvl1.setObjectName("btn_vrb_lvl1")
        self.gridLayout_3.addWidget(self.btn_vrb_lvl1, 2, 3, 1, 1)
        self.btn_vrb_lvl3 = QtWidgets.QPushButton(self.content_frame)
        self.btn_vrb_lvl3.setMinimumSize(QtCore.QSize(0, 60))
        self.btn_vrb_lvl3.setMaximumSize(QtCore.QSize(260, 16777215))
        self.btn_vrb_lvl3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_vrb_lvl3.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(102, 109, 198); \n"
"font: 700 20pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.btn_vrb_lvl3.setObjectName("btn_vrb_lvl3")
        self.gridLayout_3.addWidget(self.btn_vrb_lvl3, 3, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.content_frame)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(40)
        font.setBold(True)
        font.setItalic(False)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(255, 202, 71);\n"
"\n"
"background-color: rgba(255, 255, 255,0);\n"
"font: 700 40pt \"Verdana\";")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 2)
        self.btn_adj_lvl1 = QtWidgets.QPushButton(self.content_frame)
        self.btn_adj_lvl1.setMinimumSize(QtCore.QSize(0, 60))
        self.btn_adj_lvl1.setMaximumSize(QtCore.QSize(260, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        self.btn_adj_lvl1.setFont(font)
        self.btn_adj_lvl1.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_adj_lvl1.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(102, 109, 198); \n"
"font: 700 20pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);\n"
"\n"
"")
        self.btn_adj_lvl1.setObjectName("btn_adj_lvl1")
        self.gridLayout_3.addWidget(self.btn_adj_lvl1, 2, 0, 1, 1)
        self.btn_adj_lvl2 = QtWidgets.QPushButton(self.content_frame)
        self.btn_adj_lvl2.setMinimumSize(QtCore.QSize(0, 60))
        self.btn_adj_lvl2.setMaximumSize(QtCore.QSize(260, 16777215))
        self.btn_adj_lvl2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_adj_lvl2.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(102, 109, 198); \n"
"font: 700 20pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.btn_adj_lvl2.setObjectName("btn_adj_lvl2")
        self.gridLayout_3.addWidget(self.btn_adj_lvl2, 2, 1, 1, 1)
        self.btn_vrb_lvl4 = QtWidgets.QPushButton(self.content_frame)
        self.btn_vrb_lvl4.setMinimumSize(QtCore.QSize(0, 60))
        self.btn_vrb_lvl4.setMaximumSize(QtCore.QSize(260, 16777215))
        self.btn_vrb_lvl4.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_vrb_lvl4.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(102, 109, 198); \n"
"font: 700 20pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.btn_vrb_lvl4.setObjectName("btn_vrb_lvl4")
        self.gridLayout_3.addWidget(self.btn_vrb_lvl4, 3, 4, 1, 1)
        self.btn_adj_lvl3 = QtWidgets.QPushButton(self.content_frame)
        self.btn_adj_lvl3.setMinimumSize(QtCore.QSize(0, 60))
        self.btn_adj_lvl3.setMaximumSize(QtCore.QSize(260, 16777215))
        self.btn_adj_lvl3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_adj_lvl3.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(102, 109, 198); \n"
"font: 700 20pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.btn_adj_lvl3.setObjectName("btn_adj_lvl3")
        self.gridLayout_3.addWidget(self.btn_adj_lvl3, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 150, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.gridLayout_3.addItem(spacerItem1, 4, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.content_frame)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(40)
        font.setBold(True)
        font.setItalic(False)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(255, 202, 71);\n"
"background-color: rgba(255, 255, 255,0);\n"
"font: 700 40pt \"Verdana\";")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 3, 1, 2)
        self.btn_vrb_lvl2 = QtWidgets.QPushButton(self.content_frame)
        self.btn_vrb_lvl2.setMinimumSize(QtCore.QSize(0, 60))
        self.btn_vrb_lvl2.setMaximumSize(QtCore.QSize(260, 16777215))
        self.btn_vrb_lvl2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_vrb_lvl2.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(102, 109, 198); \n"
"font: 700 20pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.btn_vrb_lvl2.setObjectName("btn_vrb_lvl2")
        self.gridLayout_3.addWidget(self.btn_vrb_lvl2, 2, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 3, 2, 1, 1)
        self.btn_adj_lvl4 = QtWidgets.QPushButton(self.content_frame)
        self.btn_adj_lvl4.setMinimumSize(QtCore.QSize(0, 60))
        self.btn_adj_lvl4.setMaximumSize(QtCore.QSize(260, 16777215))
        self.btn_adj_lvl4.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_adj_lvl4.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(102, 109, 198); \n"
"font: 700 20pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.btn_adj_lvl4.setObjectName("btn_adj_lvl4")
        self.gridLayout_3.addWidget(self.btn_adj_lvl4, 3, 1, 1, 1)
        self.gridLayout_5.addWidget(self.content_frame, 1, 0, 1, 1)
        self.main_menu.addWidget(self.vocabulaire_page)
        self.grammar_page = QtWidgets.QWidget()
        self.grammar_page.setObjectName("grammar_page")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.vocabulaire_page)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setSpacing(0)
        self.gridLayout_10.setObjectName("gridLayout_5")
        self.title_frame_2 = QtWidgets.QFrame(self.grammar_page)
        self.title_frame_2.setGeometry(QtCore.QRect(0, 0, 1135, 200))
        self.title_frame_2.setMaximumSize(QtCore.QSize(16777215, 200))
        self.title_frame_2.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.title_frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.title_frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.title_frame_2.setObjectName("title_frame_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.title_frame_2)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_7 = QtWidgets.QLabel(self.title_frame_2)
        font = QtGui.QFont()
        font.setFamily("Sitka Heading Semibold")
        font.setPointSize(61)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:rgb(255, 202, 71);\n"
"background-color: rgba(255, 255, 255,0);")
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 0, 0, 1, 1)
        self.content_frame_2 = QtWidgets.QFrame(self.grammar_page)
        self.content_frame_2.setGeometry(QtCore.QRect(0, 200, 1135, 678))
        self.content_frame_2.setStyleSheet("background-color: rgba(255, 255, 255,0);")
        self.content_frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.content_frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.content_frame_2.setObjectName("content_frame_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.content_frame_2)
        self.gridLayout_7.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.gridLayout_7.setContentsMargins(50, 0, 23, 0)
        self.gridLayout_7.setHorizontalSpacing(16)
        self.gridLayout_7.setVerticalSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.btn_vrb_lvl1_3 = QtWidgets.QPushButton(self.content_frame_2)
        self.btn_vrb_lvl1_3.setMinimumSize(QtCore.QSize(0, 60))
        self.btn_vrb_lvl1_3.setMaximumSize(QtCore.QSize(260, 16777215))
        self.btn_vrb_lvl1_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_vrb_lvl1_3.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(102, 109, 198); \n"
"font: 700 20pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.btn_vrb_lvl1_3.setObjectName("btn_vrb_lvl1_3")
        self.gridLayout_7.addWidget(self.btn_vrb_lvl1_3, 2, 3, 1, 1)
        self.btn_vrb_lvl3_3 = QtWidgets.QPushButton(self.content_frame_2)
        self.btn_vrb_lvl3_3.setMinimumSize(QtCore.QSize(0, 60))
        self.btn_vrb_lvl3_3.setMaximumSize(QtCore.QSize(260, 16777215))
        self.btn_vrb_lvl3_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_vrb_lvl3_3.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(102, 109, 198); \n"
"font: 700 20pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.btn_vrb_lvl3_3.setObjectName("btn_vrb_lvl3_3")
        self.gridLayout_7.addWidget(self.btn_vrb_lvl3_3, 3, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.content_frame_2)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(40)
        font.setBold(True)
        font.setItalic(False)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color:rgb(255, 202, 71);\n"
"\n"
"background-color: rgba(255, 255, 255,0);\n"
"font: 700 40pt \"Verdana\";")
        self.label_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 1, 0, 1, 2)
        self.btn_adj_lvl1_3 = QtWidgets.QPushButton(self.content_frame_2)
        self.btn_adj_lvl1_3.setMinimumSize(QtCore.QSize(0, 60))
        self.btn_adj_lvl1_3.setMaximumSize(QtCore.QSize(260, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        self.btn_adj_lvl1_3.setFont(font)
        self.btn_adj_lvl1_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_adj_lvl1_3.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(102, 109, 198); \n"
"font: 700 20pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);\n"
"\n"
"")
        self.btn_adj_lvl1_3.setObjectName("btn_adj_lvl1_3")
        self.gridLayout_7.addWidget(self.btn_adj_lvl1_3, 2, 0, 1, 1)
        self.btn_adj_lvl2_3 = QtWidgets.QPushButton(self.content_frame_2)
        self.btn_adj_lvl2_3.setMinimumSize(QtCore.QSize(0, 60))
        self.btn_adj_lvl2_3.setMaximumSize(QtCore.QSize(260, 16777215))
        self.btn_adj_lvl2_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_adj_lvl2_3.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(102, 109, 198); \n"
"font: 700 20pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.btn_adj_lvl2_3.setObjectName("btn_adj_lvl2_3")
        self.gridLayout_7.addWidget(self.btn_adj_lvl2_3, 2, 1, 1, 1)
        self.btn_vrb_lvl4_3 = QtWidgets.QPushButton(self.content_frame_2)
        self.btn_vrb_lvl4_3.setMinimumSize(QtCore.QSize(0, 60))
        self.btn_vrb_lvl4_3.setMaximumSize(QtCore.QSize(260, 16777215))
        self.btn_vrb_lvl4_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_vrb_lvl4_3.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(102, 109, 198); \n"
"font: 700 20pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.btn_vrb_lvl4_3.setObjectName("btn_vrb_lvl4_3")
        self.gridLayout_7.addWidget(self.btn_vrb_lvl4_3, 3, 4, 1, 1)
        self.btn_adj_lvl3_3 = QtWidgets.QPushButton(self.content_frame_2)
        self.btn_adj_lvl3_3.setMinimumSize(QtCore.QSize(0, 60))
        self.btn_adj_lvl3_3.setMaximumSize(QtCore.QSize(260, 16777215))
        self.btn_adj_lvl3_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_adj_lvl3_3.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(102, 109, 198); \n"
"font: 700 20pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.btn_adj_lvl3_3.setObjectName("btn_adj_lvl3_3")
        self.gridLayout_7.addWidget(self.btn_adj_lvl3_3, 3, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 150, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.gridLayout_7.addItem(spacerItem3, 4, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.content_frame_2)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(40)
        font.setBold(True)
        font.setItalic(False)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:rgb(255, 202, 71);\n"
"background-color: rgba(255, 255, 255,0);\n"
"font: 700 40pt \"Verdana\";")
        self.label_9.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 1, 3, 1, 2)
        self.btn_vrb_lvl2_3 = QtWidgets.QPushButton(self.content_frame_2)
        self.btn_vrb_lvl2_3.setMinimumSize(QtCore.QSize(0, 60))
        self.btn_vrb_lvl2_3.setMaximumSize(QtCore.QSize(260, 16777215))
        self.btn_vrb_lvl2_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_vrb_lvl2_3.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(102, 109, 198); \n"
"font: 700 20pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.btn_vrb_lvl2_3.setObjectName("btn_vrb_lvl2_3")
        self.gridLayout_7.addWidget(self.btn_vrb_lvl2_3, 2, 4, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_7.addItem(spacerItem4, 3, 2, 1, 1)
        self.btn_adj_lvl4_3 = QtWidgets.QPushButton(self.content_frame_2)
        self.btn_adj_lvl4_3.setMinimumSize(QtCore.QSize(0, 60))
        self.btn_adj_lvl4_3.setMaximumSize(QtCore.QSize(260, 16777215))
        self.btn_adj_lvl4_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_adj_lvl4_3.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(102, 109, 198); \n"
"font: 700 20pt \"Tahoma\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.btn_adj_lvl4_3.setObjectName("btn_adj_lvl4_3")
        self.gridLayout_7.addWidget(self.btn_adj_lvl4_3, 3, 1, 1, 1)
        self.main_menu.addWidget(self.grammar_page)
        self.gridLayout_4.addWidget(self.main_menu, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolButton_4.setText(_translate("MainWindow", "Evaluation"))
        self.toolButton.setText(_translate("MainWindow", "Vocabulaire"))
        self.toolButton_3.setText(_translate("MainWindow", "Conjugaison"))
        self.toolButton_2.setText(_translate("MainWindow", "Grammaire"))
        self.label.setText(_translate("MainWindow", "Révision de vocabulaire"))
        self.btn_vrb_lvl1.setText(_translate("MainWindow", "Niveau 0"))
        self.btn_vrb_lvl3.setText(_translate("MainWindow", "Niveau 2"))
        self.label_2.setText(_translate("MainWindow", "Adjectifs"))
        self.btn_adj_lvl1.setText(_translate("MainWindow", "Niveau 0"))
        self.btn_adj_lvl2.setText(_translate("MainWindow", "Niveau 1"))
        self.btn_vrb_lvl4.setText(_translate("MainWindow", "Niveau 3"))
        self.btn_adj_lvl3.setText(_translate("MainWindow", "Niveau 2"))
        self.label_3.setText(_translate("MainWindow", "Verbes"))
        self.btn_vrb_lvl2.setText(_translate("MainWindow", "Niveau 1"))
        self.btn_adj_lvl4.setText(_translate("MainWindow", "Niveau 3"))
        self.label_7.setText(_translate("MainWindow", "Révision de vocabulaire"))
        self.btn_vrb_lvl1_3.setText(_translate("MainWindow", "Niveau 0"))
        self.btn_vrb_lvl3_3.setText(_translate("MainWindow", "Niveau 2"))
        self.label_8.setText(_translate("MainWindow", "d"))
        self.btn_adj_lvl1_3.setText(_translate("MainWindow", "Niveau 0"))
        self.btn_adj_lvl2_3.setText(_translate("MainWindow", "Niveau 1"))
        self.btn_vrb_lvl4_3.setText(_translate("MainWindow", "Niveau 3"))
        self.btn_adj_lvl3_3.setText(_translate("MainWindow", "Niveau 2"))
        self.label_9.setText(_translate("MainWindow", "Verbes"))
        self.btn_vrb_lvl2_3.setText(_translate("MainWindow", "Niveau 1"))
        self.btn_adj_lvl4_3.setText(_translate("MainWindow", "Niveau 3"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
