# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'conjugationLevelPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(596, 611)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet(
            "background-color:qlineargradient(spread:pad, x1:0.511737, y1:0, x2:0.526, y2:1, stop:0 rgba(242, 131, 157, 255), stop:1 rgba(255, 193, 196, 255))")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.content_frame = QtWidgets.QFrame(self.centralwidget)
        self.content_frame.setStyleSheet(
            "background-color: rgb(a255, 255, 255,0);")
        self.content_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_frame.setObjectName("content_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.content_frame)
        self.gridLayout_2.setContentsMargins(9, 21, 9, 20)
        self.gridLayout_2.setHorizontalSpacing(70)
        self.gridLayout_2.setVerticalSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.word3_guess = QtWidgets.QLineEdit(self.content_frame)
        self.word3_guess.setMaximumSize(QtCore.QSize(260, 16777215))
        self.word3_guess.setStyleSheet("border-radius:10px;\n"
                                       "background-color: rgba(255, 239, 233, 250);\n"
                                       "font: 20pt \"Calisto MT\";\n"
                                       "color: rgb(43, 43, 43);")
        self.word3_guess.setAlignment(QtCore.Qt.AlignCenter)
        self.word3_guess.setObjectName("word3_guess")
        self.gridLayout_2.addWidget(self.word3_guess, 6, 1, 1, 1)
        self.word2_guess = QtWidgets.QLineEdit(self.content_frame)
        self.word2_guess.setMaximumSize(QtCore.QSize(260, 16777215))
        self.word2_guess.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.word2_guess.setAutoFillBackground(False)
        self.word2_guess.setStyleSheet("border-radius:10px;\n"
                                       "background-color: rgba(255, 239, 233, 250);\n"
                                       "font: 20pt \"Calisto MT\";\n"
                                       "color: rgb(43, 43, 43);")
        self.word2_guess.setText("")
        self.word2_guess.setAlignment(
            QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.word2_guess.setObjectName("word2_guess")
        self.gridLayout_2.addWidget(self.word2_guess, 5, 1, 1, 1)
        self.word1_guess = QtWidgets.QLineEdit(self.content_frame)
        self.word1_guess.setMaximumSize(QtCore.QSize(260, 16777215))
        self.word1_guess.setStyleSheet("border-radius:10px;\n"
                                       "background-color: rgba(255, 239, 233, 250);\n"
                                       "font: 20pt \"Calisto MT\";\n"
                                       "color: rgb(43, 43, 43);")
        self.word1_guess.setAlignment(QtCore.Qt.AlignCenter)
        self.word1_guess.setObjectName("word1_guess")
        self.gridLayout_2.addWidget(self.word1_guess, 4, 1, 1, 1)
        self.word4_guess = QtWidgets.QLineEdit(self.content_frame)
        self.word4_guess.setMaximumSize(QtCore.QSize(260, 16777215))
        self.word4_guess.setStyleSheet("border-radius:10px;\n"
                                       "background-color: rgba(255, 239, 233, 250);\n"
                                       "font: 20pt \"Calisto MT\";\n"
                                       "color: rgb(43, 43, 43);")
        self.word4_guess.setAlignment(QtCore.Qt.AlignCenter)
        self.word4_guess.setObjectName("word4_guess")
        self.gridLayout_2.addWidget(self.word4_guess, 7, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.content_frame)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
                                   "font: 700 26pt \"Verdana\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 4, 0, 1, 1)
        self.lvl_verb = QtWidgets.QPushButton(self.content_frame)
        self.lvl_verb.setMinimumSize(QtCore.QSize(0, 50))
        self.lvl_verb.setMaximumSize(QtCore.QSize(260, 16777215))
        self.lvl_verb.setStyleSheet("border-radius:20px;\n"
                                    "background-color:rgb(39, 198, 209);\n"
                                    "border-color: rgb(108, 108, 108);\n"
                                    "font: 700 24pt \"Book Antiqua\";\n"
                                    "color:rgb(225, 255, 255);")
        self.lvl_verb.setObjectName("lvl_verb")
        self.gridLayout_2.addWidget(self.lvl_verb, 6, 2, 1, 1)
        self.word5_guess = QtWidgets.QLineEdit(self.content_frame)
        self.word5_guess.setMaximumSize(QtCore.QSize(260, 16777215))
        self.word5_guess.setStyleSheet("border-radius:10px;\n"
                                       "background-color: rgba(255, 239, 233, 250);\n"
                                       "font: 20pt \"Calisto MT\";\n"
                                       "color: rgb(43, 43, 43);")
        self.word5_guess.setAlignment(QtCore.Qt.AlignCenter)
        self.word5_guess.setObjectName("word5_guess")
        self.gridLayout_2.addWidget(self.word5_guess, 8, 1, 1, 1)
        self.word6_guess = QtWidgets.QLineEdit(self.content_frame)
        self.word6_guess.setMaximumSize(QtCore.QSize(260, 16777215))
        self.word6_guess.setStyleSheet("border-radius:10px;\n"
                                       "background-color: rgba(255, 239, 233, 250);\n"
                                       "font: 20pt \"Calisto MT\";\n"
                                       "color: rgb(43, 43, 43);")
        self.word6_guess.setAlignment(QtCore.Qt.AlignCenter)
        self.word6_guess.setObjectName("word6_guess")
        self.gridLayout_2.addWidget(self.word6_guess, 9, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.content_frame)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
                                   "font: 700 26pt \"Verdana\";")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 5, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.content_frame)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
                                   "font: 700 26pt \"Verdana\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 6, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.content_frame)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
                                   "font: 700 26pt \"Verdana\";")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 7, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.content_frame)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);\n"
                                   "font: 700 26pt \"Verdana\";")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 8, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.content_frame)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);\n"
                                   "font: 700 26pt \"Verdana\";")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 9, 0, 1, 1)
        self.gridLayout_3.addWidget(self.content_frame, 1, 0, 1, 1)
        self.title_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.title_frame.sizePolicy().hasHeightForWidth())
        self.title_frame.setSizePolicy(sizePolicy)
        self.title_frame.setMaximumSize(QtCore.QSize(16777215, 200))
        self.title_frame.setStyleSheet(
            "background-color: rgb(a255, 255, 255,0);")
        self.title_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame.setObjectName("title_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.title_frame)
        self.gridLayout.setContentsMargins(9, 0, 9, 8)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(8)
        self.gridLayout.setObjectName("gridLayout")
        self.lvl_question = QtWidgets.QLabel(self.title_frame)
        self.lvl_question.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lvl_question.setStyleSheet("color: rgb(255, 255, 255);\n"
                                        "font: italic 18pt \"Verdana\";")
        self.lvl_question.setAlignment(QtCore.Qt.AlignCenter)
        self.lvl_question.setObjectName("lvl_question")
        self.gridLayout.addWidget(self.lvl_question, 1, 2, 1, 1)
        self.btn_goto_menu = QtWidgets.QPushButton(self.title_frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_goto_menu.sizePolicy().hasHeightForWidth())
        self.btn_goto_menu.setSizePolicy(sizePolicy)
        self.btn_goto_menu.setMinimumSize(QtCore.QSize(140, 50))
        self.btn_goto_menu.setMaximumSize(QtCore.QSize(140, 50))
        self.btn_goto_menu.setStyleSheet("background-color: rgb(200, 28, 30);\n"
                                         "color: white;\n"
                                         "font: 600 16pt \"Segoe UI Semibold\";\n"
                                         "border-radius: 10px;")
        self.btn_goto_menu.setObjectName("btn_goto_menu")
        self.gridLayout.addWidget(self.btn_goto_menu, 0, 3, 1, 1)
        self.btn_correct = QtWidgets.QPushButton(self.title_frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_correct.sizePolicy().hasHeightForWidth())
        self.btn_correct.setSizePolicy(sizePolicy)
        self.btn_correct.setMinimumSize(QtCore.QSize(180, 60))
        self.btn_correct.setMaximumSize(QtCore.QSize(140, 50))
        self.btn_correct.setStyleSheet("background-color: rgb(0, 210, 0);\n"
                                       "border-radius: 10px;\n"
                                       "color: rgb(252, 255, 234);\n"
                                       "font: 700 18pt \"Segoe UI Variable Text\";")
        self.btn_correct.setObjectName("btn_correct")
        self.gridLayout.addWidget(self.btn_correct, 0, 1, 1, 1)
        self.lvl_title = QtWidgets.QLabel(self.title_frame)
        self.lvl_title.setMinimumSize(QtCore.QSize(20, 0))
        self.lvl_title.setMaximumSize(QtCore.QSize(16777215, 120))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(64)
        font.setBold(True)
        font.setItalic(False)
        self.lvl_title.setFont(font)
        self.lvl_title.setStyleSheet("color:rgb(193, 1, 42);\n"
                                     "font: 700 64pt \"Tw Cen MT\";")
        self.lvl_title.setAlignment(
            QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.lvl_title.setObjectName("lvl_title")
        self.gridLayout.addWidget(self.lvl_title, 0, 2, 1, 1)
        self.gridLayout_3.addWidget(self.title_frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Je"))
        self.lvl_verb.setText(_translate("MainWindow", "mot2"))
        self.label_3.setText(_translate("MainWindow", "Tu"))
        self.label_4.setText(_translate("MainWindow", "Il/Elle/On"))
        self.label_5.setText(_translate("MainWindow", "Nous"))
        self.label_6.setText(_translate("MainWindow", "Vous"))
        self.label_7.setText(_translate("MainWindow", "Ils/Elles"))
        self.lvl_question.setText(_translate("MainWindow", "TextLabel"))
        self.btn_goto_menu.setText(_translate("MainWindow", "Au menu"))
        self.btn_correct.setText(_translate("MainWindow", "Corriger"))
        self.lvl_title.setText(_translate("MainWindow", "Titre "))
