# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'conjugationMenuPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1225, 534)
        MainWindow.setStyleSheet("border-radius: 1px")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:1, y1:0.21, x2:1, y2:1, stop:0 rgba(199, 103, 107, 255), stop:1 rgba(248, 161, 121, 255));")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.side_menu = QtWidgets.QFrame(self.centralwidget)
        self.side_menu.setMinimumSize(QtCore.QSize(0, 0))
        self.side_menu.setMaximumSize(QtCore.QSize(300, 16777215))
        self.side_menu.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.side_menu.setStyleSheet("background-color: rgb(157, 81, 88);")
        self.side_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.side_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.side_menu.setObjectName("side_menu")
        self.gridLayout = QtWidgets.QGridLayout(self.side_menu)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.toolButton = QtWidgets.QToolButton(self.side_menu)
        self.toolButton.setEnabled(False)
        self.toolButton.setMaximumSize(QtCore.QSize(500, 70))
        self.toolButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton.setStyleSheet("background-color: rgba(255, 202, 71,70);\n"
                                      "border-radius: 20px;\n"
                                      "color: rgba(255, 255,255,200);\n"
                                      "font: 700 22pt \"Segoe UI Variable Display\";")
        self.toolButton.setObjectName("toolButton")
        self.gridLayout.addWidget(self.toolButton, 5, 0, 1, 1)
        self.btn_to_gram = QtWidgets.QToolButton(self.side_menu)
        self.btn_to_gram.setMaximumSize(QtCore.QSize(500, 70))
        self.btn_to_gram.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_to_gram.setStyleSheet("background-color: rgb(255, 202, 71);\n"
                                       "border-radius: 20px;\n"
                                       "color: white;\n"
                                       "font: 700 22pt \"Segoe UI Variable Display\";")
        self.btn_to_gram.setObjectName("btn_to_gram")
        self.gridLayout.addWidget(self.btn_to_gram, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(
            41, 56, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.btn_to_vocab = QtWidgets.QToolButton(self.side_menu)
        self.btn_to_vocab.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_to_vocab.sizePolicy().hasHeightForWidth())
        self.btn_to_vocab.setSizePolicy(sizePolicy)
        self.btn_to_vocab.setMaximumSize(QtCore.QSize(500, 70))
        self.btn_to_vocab.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_to_vocab.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_to_vocab.setStyleSheet("background-color: rgb(255, 202, 71);\n"
                                        "border-radius: 20px;\n"
                                        "color: white;\n"
                                        "font: 700 22pt \"Segoe UI Variable Display\";")
        self.btn_to_vocab.setObjectName("btn_to_vocab")
        self.gridLayout.addWidget(self.btn_to_vocab, 2, 0, 1, 1)
        self.gridLayout_4.addWidget(self.side_menu, 0, 0, 1, 1)
        self.main_menu = QtWidgets.QWidget(self.centralwidget)
        self.main_menu.setObjectName("main_menu")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.main_menu)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.title_frame = QtWidgets.QFrame(self.main_menu)
        self.title_frame.setMaximumSize(QtCore.QSize(16777215, 200))
        self.title_frame.setStyleSheet(
            "background-color: rgba(255, 255, 255,0);")
        self.title_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame.setObjectName("title_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.title_frame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.title_frame)
        font = QtGui.QFont()
        font.setFamily("Sitka Heading Semibold")
        font.setPointSize(56)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(255, 202, 71);\n"
                                 "background-color: rgba(255, 255, 255,0);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.title_frame, 0, 0, 1, 1)
        self.content_frame = QtWidgets.QFrame(self.main_menu)
        self.content_frame.setStyleSheet(
            "background-color: rgba(255, 255, 255,0);")
        self.content_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_frame.setObjectName("content_frame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.content_frame)
        self.gridLayout_6.setHorizontalSpacing(10)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_2 = QtWidgets.QLabel(self.content_frame)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(255, 202, 71);\n"
                                   "\n"
                                   "background-color: rgba(255, 255, 255,0);\n"
                                   "font: 700 22pt \"Verdana\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.content_frame)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(255, 202, 71);\n"
                                   "background-color: rgba(255, 255, 255,0);\n"
                                   "font: 700 22pt \"Verdana\";")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.content_frame)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgb(255, 202, 71);\n"
                                   "background-color: rgba(255, 255, 255,0);\n"
                                   "font: 700 22pt \"Verdana\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 0, 2, 1, 1)
        self.frame = QtWidgets.QFrame(self.content_frame)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_5.setContentsMargins(0, 17, 0, 0)
        self.gridLayout_5.setHorizontalSpacing(30)
        self.gridLayout_5.setVerticalSpacing(16)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.btn_gr1_pr = QtWidgets.QPushButton(self.frame)
        self.btn_gr1_pr.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_gr1_pr.setMaximumSize(QtCore.QSize(260, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        self.btn_gr1_pr.setFont(font)
        self.btn_gr1_pr.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_gr1_pr.setStyleSheet("border-radius:20px;\n"
                                      "background-color:rgb(102, 109, 198); \n"
                                      "font: 700 16pt \"Tahoma\";\n"
                                      "color: rgb(255, 255, 255);\n"
                                      "\n"
                                      "")
        self.btn_gr1_pr.setObjectName("btn_gr1_pr")
        self.gridLayout_5.addWidget(self.btn_gr1_pr, 0, 0, 1, 1)
        self.btn_gr2_pr = QtWidgets.QPushButton(self.frame)
        self.btn_gr2_pr.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_gr2_pr.setMaximumSize(QtCore.QSize(260, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        self.btn_gr2_pr.setFont(font)
        self.btn_gr2_pr.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_gr2_pr.setStyleSheet("border-radius:20px;\n"
                                      "background-color:rgb(102, 109, 198); \n"
                                      "font: 700 16pt \"Tahoma\";\n"
                                      "color: rgb(255, 255, 255);\n"
                                      "\n"
                                      "")
        self.btn_gr2_pr.setObjectName("btn_gr2_pr")
        self.gridLayout_5.addWidget(self.btn_gr2_pr, 0, 1, 1, 1)
        self.btn_gr3_pr = QtWidgets.QPushButton(self.frame)
        self.btn_gr3_pr.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_gr3_pr.setMaximumSize(QtCore.QSize(260, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        self.btn_gr3_pr.setFont(font)
        self.btn_gr3_pr.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_gr3_pr.setStyleSheet("border-radius:20px;\n"
                                      "background-color:rgb(102, 109, 198); \n"
                                      "font: 700 16pt \"Tahoma\";\n"
                                      "color: rgb(255, 255, 255);\n"
                                      "\n"
                                      "")
        self.btn_gr3_pr.setObjectName("btn_gr3_pr")
        self.gridLayout_5.addWidget(self.btn_gr3_pr, 0, 2, 1, 1)
        self.btn_gr1_fu = QtWidgets.QPushButton(self.frame)
        self.btn_gr1_fu.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_gr1_fu.setMaximumSize(QtCore.QSize(260, 16777215))
        self.btn_gr1_fu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_gr1_fu.setStyleSheet("border-radius:20px;\n"
                                      "background-color:rgb(102, 109, 198); \n"
                                      "font: 700 16pt \"Tahoma\";\n"
                                      "color: rgb(255, 255, 255);\n"
                                      "\n"
                                      "")
        self.btn_gr1_fu.setObjectName("btn_gr1_fu")
        self.gridLayout_5.addWidget(self.btn_gr1_fu, 1, 0, 1, 1)
        self.btn_gr2_fu = QtWidgets.QPushButton(self.frame)
        self.btn_gr2_fu.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_gr2_fu.setMaximumSize(QtCore.QSize(260, 16777215))
        self.btn_gr2_fu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_gr2_fu.setStyleSheet("border-radius:20px;\n"
                                      "background-color:rgb(102, 109, 198); \n"
                                      "font: 700 16pt \"Tahoma\";\n"
                                      "color: rgb(255, 255, 255);\n"
                                      "\n"
                                      "")
        self.btn_gr2_fu.setObjectName("btn_gr2_fu")
        self.gridLayout_5.addWidget(self.btn_gr2_fu, 1, 1, 1, 1)
        self.btn_gr3_fu = QtWidgets.QPushButton(self.frame)
        self.btn_gr3_fu.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_gr3_fu.setMaximumSize(QtCore.QSize(260, 16777215))
        self.btn_gr3_fu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_gr3_fu.setStyleSheet("border-radius:20px;\n"
                                      "background-color:rgb(102, 109, 198); \n"
                                      "font: 700 16pt \"Tahoma\";\n"
                                      "color: rgb(255, 255, 255);\n"
                                      "\n"
                                      "")
        self.btn_gr3_fu.setObjectName("btn_gr3_fu")
        self.gridLayout_5.addWidget(self.btn_gr3_fu, 1, 2, 1, 1)
        self.btn_gr1_im = QtWidgets.QPushButton(self.frame)
        self.btn_gr1_im.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_gr1_im.setMaximumSize(QtCore.QSize(260, 16777215))
        self.btn_gr1_im.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_gr1_im.setStyleSheet("border-radius:20px;\n"
                                      "background-color:rgb(102, 109, 198); \n"
                                      "font: 700 16pt \"Tahoma\";\n"
                                      "color: rgb(255, 255, 255);\n"
                                      "\n"
                                      "")
        self.btn_gr1_im.setObjectName("btn_gr1_im")
        self.gridLayout_5.addWidget(self.btn_gr1_im, 2, 0, 1, 1)
        self.btn_gr2_im = QtWidgets.QPushButton(self.frame)
        self.btn_gr2_im.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_gr2_im.setMaximumSize(QtCore.QSize(260, 16777215))
        self.btn_gr2_im.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_gr2_im.setStyleSheet("border-radius:20px;\n"
                                      "background-color:rgb(102, 109, 198); \n"
                                      "font: 700 16pt \"Tahoma\";\n"
                                      "color: rgb(255, 255, 255);\n"
                                      "\n"
                                      "")
        self.btn_gr2_im.setObjectName("btn_gr2_im")
        self.gridLayout_5.addWidget(self.btn_gr2_im, 2, 1, 1, 1)
        self.btn_gr3_im = QtWidgets.QPushButton(self.frame)
        self.btn_gr3_im.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_gr3_im.setMaximumSize(QtCore.QSize(260, 16777215))
        self.btn_gr3_im.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_gr3_im.setStyleSheet("border-radius:20px;\n"
                                      "background-color:rgb(102, 109, 198); \n"
                                      "font: 700 16pt \"Tahoma\";\n"
                                      "color: rgb(255, 255, 255);\n"
                                      "\n"
                                      "")
        self.btn_gr3_im.setObjectName("btn_gr3_im")
        self.gridLayout_5.addWidget(self.btn_gr3_im, 2, 2, 1, 1)
        self.btn_gr1_ps = QtWidgets.QPushButton(self.frame)
        self.btn_gr1_ps.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_gr1_ps.setMaximumSize(QtCore.QSize(260, 16777215))
        self.btn_gr1_ps.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_gr1_ps.setStyleSheet("border-radius:20px;\n"
                                      "background-color:rgb(102, 109, 198); \n"
                                      "font: 700 16pt \"Tahoma\";\n"
                                      "color: rgb(255, 255, 255);\n"
                                      "\n"
                                      "")
        self.btn_gr1_ps.setObjectName("btn_gr1_ps")
        self.gridLayout_5.addWidget(self.btn_gr1_ps, 3, 0, 1, 1)
        self.btn_gr2_ps = QtWidgets.QPushButton(self.frame)
        self.btn_gr2_ps.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_gr2_ps.setMaximumSize(QtCore.QSize(260, 16777215))
        self.btn_gr2_ps.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_gr2_ps.setStyleSheet("border-radius:20px;\n"
                                      "background-color:rgb(102, 109, 198); \n"
                                      "font: 700 16pt \"Tahoma\";\n"
                                      "color: rgb(255, 255, 255);\n"
                                      "\n"
                                      "")
        self.btn_gr2_ps.setObjectName("btn_gr2_ps")
        self.gridLayout_5.addWidget(self.btn_gr2_ps, 3, 1, 1, 1)
        self.btn_gr3_ps = QtWidgets.QPushButton(self.frame)
        self.btn_gr3_ps.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_gr3_ps.setMaximumSize(QtCore.QSize(260, 16777215))
        self.btn_gr3_ps.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_gr3_ps.setStyleSheet("border-radius:20px;\n"
                                      "background-color:rgb(102, 109, 198); \n"
                                      "font: 700 16pt \"Tahoma\";\n"
                                      "color: rgb(255, 255, 255);\n"
                                      "\n"
                                      "")
        self.btn_gr3_ps.setObjectName("btn_gr3_ps")
        self.gridLayout_5.addWidget(self.btn_gr3_ps, 3, 2, 1, 1)
        self.btn_gr1_pc = QtWidgets.QPushButton(self.frame)
        self.btn_gr1_pc.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_gr1_pc.setMaximumSize(QtCore.QSize(260, 16777215))
        self.btn_gr1_pc.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_gr1_pc.setStyleSheet("border-radius:20px;\n"
                                      "background-color:rgb(102, 109, 198); \n"
                                      "font: 700 16pt \"Tahoma\";\n"
                                      "color: rgb(255, 255, 255);\n"
                                      "\n"
                                      "")
        self.btn_gr1_pc.setObjectName("btn_gr1_pc")
        self.gridLayout_5.addWidget(self.btn_gr1_pc, 4, 0, 1, 1)
        self.btn_gr2_pc = QtWidgets.QPushButton(self.frame)
        self.btn_gr2_pc.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_gr2_pc.setMaximumSize(QtCore.QSize(260, 16777215))
        self.btn_gr2_pc.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_gr2_pc.setStyleSheet("border-radius:20px;\n"
                                      "background-color:rgb(102, 109, 198); \n"
                                      "font: 700 16pt \"Tahoma\";\n"
                                      "color: rgb(255, 255, 255);\n"
                                      "\n"
                                      "")
        self.btn_gr2_pc.setObjectName("btn_gr2_pc")
        self.gridLayout_5.addWidget(self.btn_gr2_pc, 4, 1, 1, 1)
        self.btn_gr3_pc = QtWidgets.QPushButton(self.frame)
        self.btn_gr3_pc.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_gr3_pc.setMaximumSize(QtCore.QSize(260, 16777215))
        self.btn_gr3_pc.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_gr3_pc.setStyleSheet("border-radius:20px;\n"
                                      "background-color:rgb(102, 109, 198); \n"
                                      "font: 700 16pt \"Tahoma\";\n"
                                      "color: rgb(255, 255, 255);\n"
                                      "\n"
                                      "")
        self.btn_gr3_pc.setObjectName("btn_gr3_pc")
        self.gridLayout_5.addWidget(self.btn_gr3_pc, 4, 2, 1, 1)
        self.gridLayout_6.addWidget(self.frame, 1, 0, 1, 3)
        self.gridLayout_3.addWidget(self.content_frame, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_3.addItem(spacerItem1, 2, 0, 1, 1)
        self.gridLayout_4.addWidget(self.main_menu, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolButton.setText(_translate("MainWindow", "Conjugaison"))
        self.btn_to_gram.setText(_translate("MainWindow", "Grammaire"))
        self.btn_to_vocab.setText(_translate("MainWindow", "Vocabulaire"))
        self.label.setText(_translate("MainWindow", "Révision de conjugaison"))
        self.label_2.setText(_translate("MainWindow", "1ère groupe"))
        self.label_3.setText(_translate("MainWindow", "2ème groupe"))
        self.label_4.setText(_translate("MainWindow", "3ème groupe"))
        self.btn_gr1_pr.setText(_translate("MainWindow", "Préssent"))
        self.btn_gr2_pr.setText(_translate("MainWindow", "Préssent"))
        self.btn_gr3_pr.setText(_translate("MainWindow", "Préssent"))
        self.btn_gr1_fu.setText(_translate("MainWindow", "Future"))
        self.btn_gr2_fu.setText(_translate("MainWindow", "Future"))
        self.btn_gr3_fu.setText(_translate("MainWindow", "Future"))
        self.btn_gr1_im.setText(_translate("MainWindow", "Imparfait"))
        self.btn_gr2_im.setText(_translate("MainWindow", "Imparfait"))
        self.btn_gr3_im.setText(_translate("MainWindow", "Imparfait"))
        self.btn_gr1_ps.setText(_translate("MainWindow", "Passé simple"))
        self.btn_gr2_ps.setText(_translate("MainWindow", "Passé simple"))
        self.btn_gr3_ps.setText(_translate("MainWindow", "Passé simple"))
        self.btn_gr1_pc.setText(_translate("MainWindow", "Passé composé"))
        self.btn_gr2_pc.setText(_translate("MainWindow", "Passé composé"))
        self.btn_gr3_pc.setText(_translate("MainWindow", "Passé composé"))
