# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CorrectionMessageBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 480)
        Dialog.setStyleSheet("background-color: rgb(1, 93, 191);\n"
                             "border-radius: 20px;")
        self.btn_tryagain = QtWidgets.QPushButton(Dialog)
        self.btn_tryagain.setGeometry(QtCore.QRect(270, 410, 131, 41))
        self.btn_tryagain.setStyleSheet("border-radius: 8px;\n"
                                        "background-color: rgb(29, 235, 64);\n"
                                        "color: rgb(255, 255, 255);\n"
                                        "font: 700 14pt \"Segoe UI\";")
        self.btn_tryagain.setObjectName("btn_tryagain")
        self.btn_goto_menu = QtWidgets.QPushButton(Dialog)
        self.btn_goto_menu.setGeometry(QtCore.QRect(530, 410, 101, 41))
        self.btn_goto_menu.setStyleSheet("border-radius: 8px;\n"
                                         "background-color: rgb(238, 31, 31);\n"
                                         "color: rgb(255, 255, 255);\n"
                                         "font: 700 12pt \"Tw Cen MT\";")
        self.btn_goto_menu.setObjectName("btn_goto_menu")
        self.msg_txt = QtWidgets.QLabel(Dialog)
        self.msg_txt.setGeometry(QtCore.QRect(30, 20, 581, 361))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.msg_txt.setFont(font)
        self.msg_txt.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.msg_txt.setStyleSheet("background-color: rgba(0,0,0,0);\n"
                                   "color: rgb(255, 255, 255);\n"
                                   "\n"
                                   "")
        self.msg_txt.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.msg_txt.setObjectName("msg_txt")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_tryagain.setText(_translate("Dialog", "Ressayer"))
        self.btn_goto_menu.setText(_translate("Dialog", "Menu"))
        self.msg_txt.setText(_translate("Dialog", "mot 1 = syn 1"))
