# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'grammarLevelPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(654, 531)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0.512, y1:0, x2:0.512, y2:1, stop:0 rgba(252, 216, 70, 255), stop:1 rgba(254, 249, 108, 255));")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.content_frame = QtWidgets.QFrame(self.centralwidget)
        self.content_frame.setStyleSheet(
            "background-color: rgb(a255, 255, 255,0);")
        self.content_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_frame.setObjectName("content_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.content_frame)
        self.gridLayout_2.setContentsMargins(9, 21, 9, 20)
        self.gridLayout_2.setHorizontalSpacing(70)
        self.gridLayout_2.setVerticalSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_word10 = QtWidgets.QPushButton(self.content_frame)
        self.btn_word10.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_word10.setMaximumSize(QtCore.QSize(260, 16777215))
        self.btn_word10.setStyleSheet("border-radius:20px;\n"
                                      "background-color:rgb(23, 182, 214);\n"
                                      "border-color: rgb(108, 108, 108);\n"
                                      "font: 700 24pt \"Book Antiqua\";\n"
                                      "color:rgb(225, 255, 255);")
        self.btn_word10.setObjectName("btn_word10")
        self.gridLayout_2.addWidget(self.btn_word10, 4, 2, 1, 1)
        self.word2_guess = QtWidgets.QLineEdit(self.content_frame)
        self.word2_guess.setMaximumSize(QtCore.QSize(260, 16777215))
        self.word2_guess.setStyleSheet("border-radius:10px;\n"
                                       "background-color: rgba(255, 239, 233, 250);\n"
                                       "font: 20pt \"Calisto MT\";\n"
                                       "color: rgb(43, 43, 43);")
        self.word2_guess.setAlignment(QtCore.Qt.AlignCenter)
        self.word2_guess.setObjectName("word2_guess")
        self.gridLayout_2.addWidget(self.word2_guess, 1, 1, 1, 1)
        self.btn_word4 = QtWidgets.QPushButton(self.content_frame)
        self.btn_word4.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_word4.setMaximumSize(QtCore.QSize(260, 16777215))
        self.btn_word4.setStyleSheet("border-radius:20px;\n"
                                     "background-color:rgb(23, 182, 214);\n"
                                     "border-color: rgb(108, 108, 108);\n"
                                     "font: 700 24pt \"Book Antiqua\";\n"
                                     "color:rgb(225, 255, 255);")
        self.btn_word4.setObjectName("btn_word4")
        self.gridLayout_2.addWidget(self.btn_word4, 2, 0, 1, 1)
        self.btn_word2 = QtWidgets.QPushButton(self.content_frame)
        self.btn_word2.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_word2.setMaximumSize(QtCore.QSize(260, 16777215))
        self.btn_word2.setStyleSheet("border-radius:20px;\n"
                                     "background-color:rgb(23, 182, 214);\n"
                                     "border-color: rgb(108, 108, 108);\n"
                                     "font: 700 24pt \"Book Antiqua\";\n"
                                     "color:rgb(225, 255, 255);")
        self.btn_word2.setObjectName("btn_word2")
        self.gridLayout_2.addWidget(self.btn_word2, 0, 2, 1, 1)
        self.word4_guess = QtWidgets.QLineEdit(self.content_frame)
        self.word4_guess.setMaximumSize(QtCore.QSize(260, 16777215))
        self.word4_guess.setStyleSheet("border-radius:10px;\n"
                                       "background-color: rgba(255, 239, 233, 250);\n"
                                       "font: 20pt \"Calisto MT\";\n"
                                       "color: rgb(43, 43, 43);")
        self.word4_guess.setAlignment(QtCore.Qt.AlignCenter)
        self.word4_guess.setObjectName("word4_guess")
        self.gridLayout_2.addWidget(self.word4_guess, 1, 3, 1, 1)
        self.word7_guess = QtWidgets.QLineEdit(self.content_frame)
        self.word7_guess.setMaximumSize(QtCore.QSize(260, 16777215))
        self.word7_guess.setStyleSheet("border-radius:10px;\n"
                                       "background-color: rgba(255, 239, 233, 250);\n"
                                       "font: 20pt \"Calisto MT\";\n"
                                       "color: rgb(43, 43, 43);")
        self.word7_guess.setAlignment(QtCore.Qt.AlignCenter)
        self.word7_guess.setObjectName("word7_guess")
        self.gridLayout_2.addWidget(self.word7_guess, 3, 2, 1, 1)
        self.word9_guess = QtWidgets.QLineEdit(self.content_frame)
        self.word9_guess.setMaximumSize(QtCore.QSize(260, 16777215))
        self.word9_guess.setStyleSheet("border-radius:10px;\n"
                                       "background-color: rgba(255, 239, 233, 250);\n"
                                       "font: 20pt \"Calisto MT\";\n"
                                       "color: rgb(43, 43, 43);")
        self.word9_guess.setAlignment(QtCore.Qt.AlignCenter)
        self.word9_guess.setObjectName("word9_guess")
        self.gridLayout_2.addWidget(self.word9_guess, 5, 0, 1, 1)
        self.word12_guess = QtWidgets.QLineEdit(self.content_frame)
        self.word12_guess.setMaximumSize(QtCore.QSize(260, 16777215))
        self.word12_guess.setStyleSheet("border-radius:10px;\n"
                                        "background-color: rgba(255, 239, 233, 250);\n"
                                        "font: 20pt \"Calisto MT\";\n"
                                        "color: rgb(43, 43, 43);")
        self.word12_guess.setAlignment(QtCore.Qt.AlignCenter)
        self.word12_guess.setObjectName("word12_guess")
        self.gridLayout_2.addWidget(self.word12_guess, 5, 3, 1, 1)
        self.btn_word8 = QtWidgets.QPushButton(self.content_frame)
        self.btn_word8.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_word8.setMaximumSize(QtCore.QSize(260, 16777215))
        self.btn_word8.setStyleSheet("border-radius:20px;\n"
                                     "background-color:rgb(23, 182, 214);\n"
                                     "border-color: rgb(108, 108, 108);\n"
                                     "font: 700 24pt \"Book Antiqua\";\n"
                                     "color:rgb(225, 255, 255);")
        self.btn_word8.setObjectName("btn_word8")
        self.gridLayout_2.addWidget(self.btn_word8, 4, 0, 1, 1)
        self.word8_guess = QtWidgets.QLineEdit(self.content_frame)
        self.word8_guess.setMaximumSize(QtCore.QSize(260, 16777215))
        self.word8_guess.setStyleSheet("border-radius:10px;\n"
                                       "background-color: rgba(255, 239, 233, 250);\n"
                                       "font: 20pt \"Calisto MT\";\n"
                                       "color: rgb(43, 43, 43);")
        self.word8_guess.setAlignment(QtCore.Qt.AlignCenter)
        self.word8_guess.setObjectName("word8_guess")
        self.gridLayout_2.addWidget(self.word8_guess, 3, 3, 1, 1)
        self.btn_word0 = QtWidgets.QPushButton(self.content_frame)
        self.btn_word0.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_word0.setMaximumSize(QtCore.QSize(260, 16777215))
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        self.btn_word0.setFont(font)
        self.btn_word0.setStyleSheet("border-radius:20px;\n"
                                     "background-color:rgb(23, 182, 214);\n"
                                     "border-color: rgb(108, 108, 108);\n"
                                     "font: 700 24pt \"Book Antiqua\";\n"
                                     "color:rgb(225, 255, 255);")
        self.btn_word0.setObjectName("btn_word0")
        self.gridLayout_2.addWidget(self.btn_word0, 0, 0, 1, 1)
        self.word10_guess = QtWidgets.QLineEdit(self.content_frame)
        self.word10_guess.setMaximumSize(QtCore.QSize(260, 16777215))
        self.word10_guess.setStyleSheet("border-radius:10px;\n"
                                        "background-color: rgba(255, 239, 233, 250);\n"
                                        "font: 20pt \"Calisto MT\";\n"
                                        "color: rgb(43, 43, 43);")
        self.word10_guess.setAlignment(QtCore.Qt.AlignCenter)
        self.word10_guess.setObjectName("word10_guess")
        self.gridLayout_2.addWidget(self.word10_guess, 5, 1, 1, 1)
        self.word6_guess = QtWidgets.QLineEdit(self.content_frame)
        self.word6_guess.setMaximumSize(QtCore.QSize(260, 16777215))
        self.word6_guess.setStyleSheet("border-radius:10px;\n"
                                       "background-color: rgba(255, 239, 233, 250);\n"
                                       "font: 20pt \"Calisto MT\";\n"
                                       "color: rgb(43, 43, 43);")
        self.word6_guess.setAlignment(QtCore.Qt.AlignCenter)
        self.word6_guess.setObjectName("word6_guess")
        self.gridLayout_2.addWidget(self.word6_guess, 3, 1, 1, 1)
        self.word5_guess = QtWidgets.QLineEdit(self.content_frame)
        self.word5_guess.setMaximumSize(QtCore.QSize(260, 16777215))
        self.word5_guess.setStyleSheet("border-radius:10px;\n"
                                       "background-color: rgba(255, 239, 233, 250);\n"
                                       "font: 20pt \"Calisto MT\";\n"
                                       "color: rgb(43, 43, 43);")
        self.word5_guess.setAlignment(QtCore.Qt.AlignCenter)
        self.word5_guess.setObjectName("word5_guess")
        self.gridLayout_2.addWidget(self.word5_guess, 3, 0, 1, 1)
        self.btn_word3 = QtWidgets.QPushButton(self.content_frame)
        self.btn_word3.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_word3.setMaximumSize(QtCore.QSize(260, 16777215))
        self.btn_word3.setStyleSheet("border-radius:20px;\n"
                                     "background-color:rgb(23, 182, 214);\n"
                                     "border-color: rgb(108, 108, 108);\n"
                                     "font: 700 24pt \"Book Antiqua\";\n"
                                     "color:rgb(225, 255, 255);")
        self.btn_word3.setObjectName("btn_word3")
        self.gridLayout_2.addWidget(self.btn_word3, 0, 3, 1, 1)
        self.btn_word7 = QtWidgets.QPushButton(self.content_frame)
        self.btn_word7.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_word7.setMaximumSize(QtCore.QSize(260, 16777215))
        self.btn_word7.setStyleSheet("border-radius:20px;\n"
                                     "background-color:rgb(23, 182, 214);\n"
                                     "border-color: rgb(108, 108, 108);\n"
                                     "font: 700 24pt \"Book Antiqua\";\n"
                                     "color:rgb(225, 255, 255);")
        self.btn_word7.setObjectName("btn_word7")
        self.gridLayout_2.addWidget(self.btn_word7, 2, 3, 1, 1)
        self.word3_guess = QtWidgets.QLineEdit(self.content_frame)
        self.word3_guess.setMaximumSize(QtCore.QSize(260, 16777215))
        self.word3_guess.setStyleSheet("border-radius:10px;\n"
                                       "background-color: rgba(255, 239, 233, 250);\n"
                                       "font: 20pt \"Calisto MT\";\n"
                                       "color: rgb(43, 43, 43);")
        self.word3_guess.setAlignment(QtCore.Qt.AlignCenter)
        self.word3_guess.setObjectName("word3_guess")
        self.gridLayout_2.addWidget(self.word3_guess, 1, 2, 1, 1)
        self.word11_guess = QtWidgets.QLineEdit(self.content_frame)
        self.word11_guess.setMaximumSize(QtCore.QSize(260, 16777215))
        self.word11_guess.setStyleSheet("border-radius:10px;\n"
                                        "background-color: rgba(255, 239, 233, 250);\n"
                                        "font: 20pt \"Calisto MT\";\n"
                                        "color: rgb(43, 43, 43);")
        self.word11_guess.setAlignment(QtCore.Qt.AlignCenter)
        self.word11_guess.setObjectName("word11_guess")
        self.gridLayout_2.addWidget(self.word11_guess, 5, 2, 1, 1)
        self.btn_word1 = QtWidgets.QPushButton(self.content_frame)
        self.btn_word1.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_word1.setMaximumSize(QtCore.QSize(260, 16777215))
        self.btn_word1.setStyleSheet("border-radius:20px;\n"
                                     "background-color:rgb(23, 182, 214);\n"
                                     "border-color: rgb(108, 108, 108);\n"
                                     "font: 700 24pt \"Book Antiqua\";\n"
                                     "color:rgb(225, 255, 255);")
        self.btn_word1.setObjectName("btn_word1")
        self.gridLayout_2.addWidget(self.btn_word1, 0, 1, 1, 1)
        self.btn_word9 = QtWidgets.QPushButton(self.content_frame)
        self.btn_word9.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_word9.setMaximumSize(QtCore.QSize(260, 16777215))
        self.btn_word9.setStyleSheet("border-radius:20px;\n"
                                     "background-color:rgb(23, 182, 214);\n"
                                     "border-color: rgb(108, 108, 108);\n"
                                     "font: 700 24pt \"Book Antiqua\";\n"
                                     "color:rgb(225, 255, 255);")
        self.btn_word9.setObjectName("btn_word9")
        self.gridLayout_2.addWidget(self.btn_word9, 4, 1, 1, 1)
        self.btn_word6 = QtWidgets.QPushButton(self.content_frame)
        self.btn_word6.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_word6.setMaximumSize(QtCore.QSize(290, 16777215))
        self.btn_word6.setStyleSheet("border-radius:20px;\n"
                                     "background-color:rgb(23, 182, 214);\n"
                                     "border-color: rgb(108, 108, 108);\n"
                                     "font: 700 24pt \"Book Antiqua\";\n"
                                     "color:rgb(225, 255, 255);")
        self.btn_word6.setObjectName("btn_word6")
        self.gridLayout_2.addWidget(self.btn_word6, 2, 2, 1, 1)
        self.btn_word11 = QtWidgets.QPushButton(self.content_frame)
        self.btn_word11.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_word11.setMaximumSize(QtCore.QSize(260, 16777215))
        self.btn_word11.setStyleSheet("border-radius:20px;\n"
                                      "background-color:rgb(23, 182, 214);\n"
                                      "border-color: rgb(108, 108, 108);\n"
                                      "font: 700 24pt \"Book Antiqua\";\n"
                                      "color:rgb(225, 255, 255);")
        self.btn_word11.setObjectName("btn_word11")
        self.gridLayout_2.addWidget(self.btn_word11, 4, 3, 1, 1)
        self.btn_word5 = QtWidgets.QPushButton(self.content_frame)
        self.btn_word5.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_word5.setMaximumSize(QtCore.QSize(260, 16777215))
        self.btn_word5.setStyleSheet("border-radius:20px;\n"
                                     "background-color:rgb(23, 182, 214);\n"
                                     "border-color: rgb(108, 108, 108);\n"
                                     "font: 700 24pt \"Book Antiqua\";\n"
                                     "color:rgb(225, 255, 255);")
        self.btn_word5.setObjectName("btn_word5")
        self.gridLayout_2.addWidget(self.btn_word5, 2, 1, 1, 1)
        self.word1_guess = QtWidgets.QLineEdit(self.content_frame)
        self.word1_guess.setMaximumSize(QtCore.QSize(260, 16777215))
        self.word1_guess.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.word1_guess.setAutoFillBackground(False)
        self.word1_guess.setStyleSheet("border-radius:10px;\n"
                                       "background-color: rgba(255, 239, 233, 250);\n"
                                       "font: 20pt \"Calisto MT\";\n"
                                       "color: rgb(43, 43, 43);")
        self.word1_guess.setText("")
        self.word1_guess.setAlignment(
            QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.word1_guess.setObjectName("word1_guess")
        self.gridLayout_2.addWidget(self.word1_guess, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.content_frame, 1, 0, 1, 1)
        self.title_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.title_frame.sizePolicy().hasHeightForWidth())
        self.title_frame.setSizePolicy(sizePolicy)
        self.title_frame.setMaximumSize(QtCore.QSize(16777215, 200))
        self.title_frame.setStyleSheet(
            "background-color: rgb(a255, 255, 255,0);")
        self.title_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame.setObjectName("title_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.title_frame)
        self.gridLayout.setContentsMargins(9, 0, 9, 8)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(8)
        self.gridLayout.setObjectName("gridLayout")
        self.lvl_title = QtWidgets.QLabel(self.title_frame)
        self.lvl_title.setMinimumSize(QtCore.QSize(100, 0))
        self.lvl_title.setMaximumSize(QtCore.QSize(16777215, 120))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(64)
        font.setBold(True)
        font.setItalic(False)
        self.lvl_title.setFont(font)
        self.lvl_title.setStyleSheet("color:rgb(214, 2, 48);\n"
                                     "font: 700 64pt \"Tw Cen MT\";")
        self.lvl_title.setAlignment(
            QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.lvl_title.setObjectName("lvl_title")
        self.gridLayout.addWidget(self.lvl_title, 0, 2, 1, 1)
        self.btn_goto_menu = QtWidgets.QPushButton(self.title_frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_goto_menu.sizePolicy().hasHeightForWidth())
        self.btn_goto_menu.setSizePolicy(sizePolicy)
        self.btn_goto_menu.setMinimumSize(QtCore.QSize(140, 50))
        self.btn_goto_menu.setMaximumSize(QtCore.QSize(140, 50))
        self.btn_goto_menu.setStyleSheet("background-color:rgb(229, 36, 39);\n"
                                         "color: white;\n"
                                         "font: 600 16pt \"Segoe UI Semibold\";\n"
                                         "border-radius: 10px;")
        self.btn_goto_menu.setObjectName("btn_goto_menu")
        self.gridLayout.addWidget(self.btn_goto_menu, 0, 3, 1, 1)
        self.btn_correct = QtWidgets.QPushButton(self.title_frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_correct.sizePolicy().hasHeightForWidth())
        self.btn_correct.setSizePolicy(sizePolicy)
        self.btn_correct.setMinimumSize(QtCore.QSize(180, 60))
        self.btn_correct.setMaximumSize(QtCore.QSize(140, 50))
        self.btn_correct.setStyleSheet("background-color: rgb(0, 212, 0);\n"
                                       "border-radius: 10px;\n"
                                       "color: rgb(252, 255, 234);\n"
                                       "font: 700 18pt \"Segoe UI Variable Text\";")
        self.btn_correct.setObjectName("btn_correct")
        self.gridLayout.addWidget(self.btn_correct, 0, 1, 1, 1)
        self.lvl_question = QtWidgets.QLabel(self.title_frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.lvl_question.sizePolicy().hasHeightForWidth())
        self.lvl_question.setSizePolicy(sizePolicy)
        self.lvl_question.setMinimumSize(QtCore.QSize(16, 30))
        self.lvl_question.setMaximumSize(QtCore.QSize(1270, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(20)
        self.lvl_question.setFont(font)
        self.lvl_question.setStyleSheet("background-color: rgba(255, 255, 255,0);\n"
                                        "color: rgb(255, 255, 255);")
        self.lvl_question.setAlignment(QtCore.Qt.AlignCenter)
        self.lvl_question.setObjectName("lvl_question")
        self.gridLayout.addWidget(self.lvl_question, 3, 2, 1, 1)
        self.gridLayout_3.addWidget(self.title_frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_word10.setText(_translate("MainWindow", "mot11"))
        self.btn_word4.setText(_translate("MainWindow", "mot5"))
        self.btn_word2.setText(_translate("MainWindow", "mot3"))
        self.btn_word8.setText(_translate("MainWindow", "mot9"))
        self.btn_word0.setText(_translate("MainWindow", "mot1"))
        self.btn_word3.setText(_translate("MainWindow", "mot4"))
        self.btn_word7.setText(_translate("MainWindow", "mot8"))
        self.btn_word1.setText(_translate("MainWindow", "mot2"))
        self.btn_word9.setText(_translate("MainWindow", "mot10"))
        self.btn_word6.setText(_translate("MainWindow", "mot7"))
        self.btn_word11.setText(_translate("MainWindow", "mot12"))
        self.btn_word5.setText(_translate("MainWindow", "mot6"))
        self.lvl_title.setText(_translate("MainWindow", "Titre "))
        self.btn_goto_menu.setText(_translate("MainWindow", "Au menu"))
        self.btn_correct.setText(_translate("MainWindow", "Corriger"))
        self.lvl_question.setText(_translate("MainWindow", "consigne"))
