# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vocabularyMenuPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1295, 404)
        MainWindow.setStyleSheet("border-radius: 1px")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:1, y1:0.21, x2:1, y2:1, stop:0 rgba(199, 103, 107, 255), stop:1 rgba(248, 161, 121, 255));")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.side_menu = QtWidgets.QFrame(self.centralwidget)
        self.side_menu.setMinimumSize(QtCore.QSize(0, 0))
        self.side_menu.setMaximumSize(QtCore.QSize(300, 16777215))
        self.side_menu.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.side_menu.setStyleSheet("background-color: rgb(157, 81, 88);")
        self.side_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.side_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.side_menu.setObjectName("side_menu")
        self.gridLayout = QtWidgets.QGridLayout(self.side_menu)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.toolButton = QtWidgets.QToolButton(self.side_menu)
        self.toolButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.toolButton.sizePolicy().hasHeightForWidth())
        self.toolButton.setSizePolicy(sizePolicy)
        self.toolButton.setMaximumSize(QtCore.QSize(500, 70))
        self.toolButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolButton.setStyleSheet("background-color: rgba(255, 202, 71,70);\n"
                                      "border-radius: 20px;\n"
                                      "color: rgba(255,255,255,200);\n"
                                      "font: 700 22pt \"Segoe UI Variable Display\";")
        self.toolButton.setObjectName("toolButton")
        self.gridLayout.addWidget(self.toolButton, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(
            41, 56, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.btn_to_conj = QtWidgets.QToolButton(self.side_menu)
        self.btn_to_conj.setMaximumSize(QtCore.QSize(500, 70))
        self.btn_to_conj.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_to_conj.setStyleSheet("background-color: rgb(255, 202, 71);\n"
                                       "border-radius: 20px;\n"
                                       "color: white;\n"
                                       "font: 700 22pt \"Segoe UI Variable Display\";")
        self.btn_to_conj.setObjectName("btn_to_conj")
        self.gridLayout.addWidget(self.btn_to_conj, 5, 0, 1, 1)
        self.btn_to_gram = QtWidgets.QToolButton(self.side_menu)
        self.btn_to_gram.setMaximumSize(QtCore.QSize(500, 70))
        self.btn_to_gram.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_to_gram.setStyleSheet("background-color: rgb(255, 202, 71);\n"
                                       "border-radius: 20px;\n"
                                       "color: white;\n"
                                       "font: 700 22pt \"Segoe UI Variable Display\";")
        self.btn_to_gram.setObjectName("btn_to_gram")
        self.gridLayout.addWidget(self.btn_to_gram, 3, 0, 1, 1)
        self.gridLayout_4.addWidget(self.side_menu, 0, 0, 1, 1)
        self.main_menu = QtWidgets.QWidget(self.centralwidget)
        self.main_menu.setObjectName("main_menu")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.main_menu)
        self.gridLayout_5.setContentsMargins(-1, 19, -1, -1)
        self.gridLayout_5.setVerticalSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.title_frame = QtWidgets.QFrame(self.main_menu)
        self.title_frame.setMaximumSize(QtCore.QSize(16777215, 200))
        self.title_frame.setStyleSheet(
            "background-color: rgba(255, 255, 255,0);")
        self.title_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_frame.setObjectName("title_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.title_frame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.title_frame)
        font = QtGui.QFont()
        font.setFamily("Sitka Heading Semibold")
        font.setPointSize(61)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(255, 202, 71);\n"
                                 "background-color: rgba(255, 255, 255,0);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.title_frame, 0, 0, 1, 1)
        self.content_frame = QtWidgets.QFrame(self.main_menu)
        self.content_frame.setStyleSheet(
            "background-color: rgba(255, 255, 255,0);")
        self.content_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_frame.setObjectName("content_frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.content_frame)
        self.gridLayout_3.setSizeConstraint(
            QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setContentsMargins(50, 14, 23, 0)
        self.gridLayout_3.setHorizontalSpacing(16)
        self.gridLayout_3.setVerticalSpacing(10)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btn_vrb_lvl0 = QtWidgets.QPushButton(self.content_frame)
        self.btn_vrb_lvl0.setMinimumSize(QtCore.QSize(0, 70))
        self.btn_vrb_lvl0.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_vrb_lvl0.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_vrb_lvl0.setStyleSheet("border-radius:20px;\n"
                                        "background-color:rgb(102, 109, 198); \n"
                                        "font: 700 20pt \"Tahoma\";\n"
                                        "color: rgb(255, 255, 255);\n"
                                        "")
        self.btn_vrb_lvl0.setObjectName("btn_vrb_lvl0")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.btn_vrb_lvl0)
        self.gridLayout_3.addWidget(self.btn_vrb_lvl0, 2, 3, 1, 1)
        self.btn_vrb_lvl2 = QtWidgets.QPushButton(self.content_frame)
        self.btn_vrb_lvl2.setMinimumSize(QtCore.QSize(0, 70))
        self.btn_vrb_lvl2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_vrb_lvl2.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_vrb_lvl2.setStyleSheet("border-radius:20px;\n"
                                        "background-color:rgb(102, 109, 198); \n"
                                        "font: 700 20pt \"Tahoma\";\n"
                                        "color: rgb(255, 255, 255);\n"
                                        "")
        self.btn_vrb_lvl2.setObjectName("btn_vrb_lvl2")
        self.buttonGroup_2.addButton(self.btn_vrb_lvl2)
        self.gridLayout_3.addWidget(self.btn_vrb_lvl2, 3, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.content_frame)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(40)
        font.setBold(True)
        font.setItalic(False)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(255, 202, 71);\n"
                                   "\n"
                                   "background-color: rgba(255, 255, 255,0);\n"
                                   "font: 700 40pt \"Verdana\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 2)
        self.btn_adj_lvl0 = QtWidgets.QPushButton(self.content_frame)
        self.btn_adj_lvl0.setMinimumSize(QtCore.QSize(0, 70))
        self.btn_adj_lvl0.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        self.btn_adj_lvl0.setFont(font)
        self.btn_adj_lvl0.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_adj_lvl0.setStyleSheet("border-radius:20px;\n"
                                        "background-color:rgb(102, 109, 198); \n"
                                        "font: 700 20pt \"Tahoma\";\n"
                                        "color: rgb(255, 255, 255);\n"
                                        "\n"
                                        "")
        self.btn_adj_lvl0.setObjectName("btn_adj_lvl0")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.btn_adj_lvl0)
        self.gridLayout_3.addWidget(self.btn_adj_lvl0, 2, 0, 1, 1)
        self.btn_adj_lvl1 = QtWidgets.QPushButton(self.content_frame)
        self.btn_adj_lvl1.setMinimumSize(QtCore.QSize(0, 70))
        self.btn_adj_lvl1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_adj_lvl1.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_adj_lvl1.setStyleSheet("border-radius:20px;\n"
                                        "background-color:rgb(102, 109, 198); \n"
                                        "font: 700 20pt \"Tahoma\";\n"
                                        "color: rgb(255, 255, 255);\n"
                                        "")
        self.btn_adj_lvl1.setObjectName("btn_adj_lvl1")
        self.buttonGroup.addButton(self.btn_adj_lvl1)
        self.gridLayout_3.addWidget(self.btn_adj_lvl1, 2, 1, 1, 1)
        self.btn_vrb_lvl3 = QtWidgets.QPushButton(self.content_frame)
        self.btn_vrb_lvl3.setMinimumSize(QtCore.QSize(0, 70))
        self.btn_vrb_lvl3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_vrb_lvl3.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_vrb_lvl3.setStyleSheet("border-radius:20px;\n"
                                        "background-color:rgb(102, 109, 198); \n"
                                        "font: 700 20pt \"Tahoma\";\n"
                                        "color: rgb(255, 255, 255);\n"
                                        "")
        self.btn_vrb_lvl3.setObjectName("btn_vrb_lvl3")
        self.buttonGroup_2.addButton(self.btn_vrb_lvl3)
        self.gridLayout_3.addWidget(self.btn_vrb_lvl3, 3, 4, 1, 1)
        self.btn_adj_lvl2 = QtWidgets.QPushButton(self.content_frame)
        self.btn_adj_lvl2.setMinimumSize(QtCore.QSize(0, 70))
        self.btn_adj_lvl2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_adj_lvl2.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_adj_lvl2.setStyleSheet("border-radius:20px;\n"
                                        "background-color:rgb(102, 109, 198); \n"
                                        "font: 700 20pt \"Tahoma\";\n"
                                        "color: rgb(255, 255, 255);\n"
                                        "")
        self.btn_adj_lvl2.setObjectName("btn_adj_lvl2")
        self.buttonGroup.addButton(self.btn_adj_lvl2)
        self.gridLayout_3.addWidget(self.btn_adj_lvl2, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(
            20, 150, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_3.addItem(spacerItem1, 4, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.content_frame)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(40)
        font.setBold(True)
        font.setItalic(False)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(255, 202, 71);\n"
                                   "background-color: rgba(255, 255, 255,0);\n"
                                   "font: 700 40pt \"Verdana\";")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 3, 1, 2)
        self.btn_vrb_lvl1 = QtWidgets.QPushButton(self.content_frame)
        self.btn_vrb_lvl1.setMinimumSize(QtCore.QSize(0, 70))
        self.btn_vrb_lvl1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_vrb_lvl1.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_vrb_lvl1.setStyleSheet("border-radius:20px;\n"
                                        "background-color:rgb(102, 109, 198); \n"
                                        "font: 700 20pt \"Tahoma\";\n"
                                        "color: rgb(255, 255, 255);\n"
                                        "")
        self.btn_vrb_lvl1.setObjectName("btn_vrb_lvl1")
        self.buttonGroup_2.addButton(self.btn_vrb_lvl1)
        self.gridLayout_3.addWidget(self.btn_vrb_lvl1, 2, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(
            30, 20, QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 3, 2, 1, 1)
        self.btn_adj_lvl3 = QtWidgets.QPushButton(self.content_frame)
        self.btn_adj_lvl3.setMinimumSize(QtCore.QSize(0, 70))
        self.btn_adj_lvl3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_adj_lvl3.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_adj_lvl3.setStyleSheet("border-radius:20px;\n"
                                        "background-color:rgb(102, 109, 198); \n"
                                        "font: 700 20pt \"Tahoma\";\n"
                                        "color: rgb(255, 255, 255);\n"
                                        "")
        self.btn_adj_lvl3.setObjectName("btn_adj_lvl3")
        self.buttonGroup.addButton(self.btn_adj_lvl3)
        self.gridLayout_3.addWidget(self.btn_adj_lvl3, 3, 1, 1, 1)
        self.gridLayout_5.addWidget(self.content_frame, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.main_menu, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolButton.setText(_translate("MainWindow", "Vocabulaire"))
        self.btn_to_conj.setText(_translate("MainWindow", "Conjugaison"))
        self.btn_to_gram.setText(_translate("MainWindow", "Grammaire"))
        self.label.setText(_translate("MainWindow", "Révision de vocabulaire"))
        self.btn_vrb_lvl0.setText(_translate("MainWindow", "Niveau 0"))
        self.btn_vrb_lvl2.setText(_translate("MainWindow", "Niveau 2"))
        self.label_2.setText(_translate("MainWindow", "Adjectifs"))
        self.btn_adj_lvl0.setText(_translate("MainWindow", "Niveau 0"))
        self.btn_adj_lvl1.setText(_translate("MainWindow", "Niveau 1"))
        self.btn_vrb_lvl3.setText(_translate("MainWindow", "Niveau 3"))
        self.btn_adj_lvl2.setText(_translate("MainWindow", "Niveau 2"))
        self.label_3.setText(_translate("MainWindow", "Verbes"))
        self.btn_vrb_lvl1.setText(_translate("MainWindow", "Niveau 1"))
        self.btn_adj_lvl3.setText(_translate("MainWindow", "Niveau 3"))
